/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes_version2;

import com.google.gson.Gson;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.ArrayList;


public class App {

    public static void main(String[] args) {

        Gson gson = new Gson();

        String oneJson = readJsonFile();
        ArrayList ayaObj = gson.fromJson(oneJson, ArrayList.class);


        URL quotesURL = null;
        String quotesData = "";
        try {
            //step1
            quotesURL = new URL("https://api.forismatic.com/api/1.0/?method=getQuote&format=json&lang=en");
            //step2
            HttpURLConnection quotesHttpURLConnection = (HttpURLConnection) quotesURL.openConnection();
            //step3
            quotesHttpURLConnection.setRequestMethod("GET");
            //step4
            InputStreamReader quoteInputStreamReader = new InputStreamReader(quotesHttpURLConnection.getInputStream());
            BufferedReader quoteBufferedReader = new BufferedReader(quoteInputStreamReader);
            quotesData = quoteBufferedReader.readLine();
//            System.out.println(quotesData);
        } catch (IOException e) {

            recentquotes[] quotesArray = gson.fromJson(oneJson, recentquotes[].class);
            int randomNumber = (int) (Math.random() * ayaObj.size());
            System.out.println(quotesArray[randomNumber]);
            return;
        }


        forismatic quote = gson.fromJson(quotesData, forismatic.class);
        recentquotes finalQuote = new recentquotes(quote.quoteAuthor, quote.quoteText);
        ayaObj.add(finalQuote);

        File queFile = new File("C:\\Users\\ayoos\\quotes_version2\\recentquotes.json");
        try (FileWriter quoteFileWriter = new FileWriter(queFile)) {
            gson.toJson(ayaObj, quoteFileWriter);
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }

        int randNum = (int) (Math.random() * ayaObj.size());
        System.out.println(ayaObj.get(randNum));


    }




    public static String readJsonFile() {
        String contentLine = "";
        String result ="";
        BufferedReader br = null;
        try {
            br = new BufferedReader(new FileReader("C:\\Users\\ayoos\\quotes_version2\\recentquotes.json"));
            contentLine = br.readLine();
            while (contentLine != null) {
//                System.out.println(contentLine);
                result += contentLine + "\n";
                contentLine = br.readLine();
            }
        } catch (IOException ioe) {
            ioe.printStackTrace();
        }
        return result;
    }
}
