/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes_version2;

import com.google.gson.Gson;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

public class App {

    public static void main(String[] args) {


        Gson gson = new Gson();
        String jsonFile = readJsonFile();
        recentquotes[] ayaObj = gson.fromJson(jsonFile, recentquotes[].class);
        int randNum = (int)(Math.random()*ayaObj.length);
        System.out.println(ayaObj[randNum]);
        
    }


    public static String readJsonFile() {
        String contentLine = "";
        String result ="";
//        "C:\\Users\\ayoos\\quotes\\recentquotes.json"
        try {
            BufferedReader br = Files.newBufferedReader(Path.of("C:\\Users\\ayoos\\quotes\\recentquotes.json"));
            contentLine = br.readLine();
            while (contentLine != null) {
//                System.out.println(contentLine);
                result += contentLine + "\n";
                contentLine = br.readLine();
            }
        } catch (IOException ioe) {
            ioe.printStackTrace();
        }
        return result;
    }


}
